# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r
language: r

warnings_are_errors: false
cache: packages

r_github_packages: rstudio/rmarkdown

script:
  - R -e "rmarkdown::render('index.Rmd')"